# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: HA-eXiT Scheduler
version: "1.2.2"
slug: example
description: Scheduler & optimizer add-on for smart grids for energy management and cost savings.
url: "https://github.com/NarcisPlan16/HA_Scheduler/tree/main/example"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  message: "Hello world..."
schema:
  message: "str?"
image: "ghcr.io/home-assistant/{arch}-addon-example"
