# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Optimal Scheduler
version: "1.2.10"
slug: optimal_scheduler
description: Scheduler & optimizer add-on for smart grids for energy management and cost savings.
url: "https://github.com/NarcisPlan16/HA_Scheduler/tree/main/optimal_scheduler"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  message: "Hello world..."
schema:
  message: "str?"
image: "ghcr.io/NarcisPlan16/{arch}-optimal_scheduler"
