# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Optimal Scheduler
version: "4.0"
slug: optimal_scheduler
description: Scheduler & optimizer add-on for smart grids for energy management and cost savings.
url: "https://github.com/NarcisPlan16/HA_Scheduler/tree/main/optimal_scheduler"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
apparmor: true
boot: manual
###############
# Try to solve api issues
homeassistant_api: true
auth_api: true
hassio_api: true
hassio_role: default
roles:
  - homeassistant
###############
map:
  - share:rw
  - addon_config:rw
  - addons:r
options:
  Consumer_asset_IDs: []
  Generator_asset_IDs: []
  Energy_Source_asset_IDs: []
  Building_consumption_IDs: []
  Simulation_code_directory: /config/OptimalScheduler/MySimulationCode
  Classes_code_directory: /config/OptimalScheduler/MyClassesCode

schema:
  Consumer_asset_IDs: 
    - match(^(.+)$) # TODO: Generate a new regex
  Generator_asset_IDs:
    - match(^(.+)$) # TODO: Generate a new regex
  Energy_Source_asset_IDs:
    - match(^(.+)$) # TODO: Generate a new regex
  Building_consumption_IDs:
    - match(^(.+)$) # TODO: Generate a new regex
  Simulation_code_directory: str
  Classes_code_directory: str

