# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Optimal Scheduler
version: "3.1"
slug: optimal_scheduler
description: Scheduler & optimizer add-on for smart grids for energy management and cost savings.
url: "https://github.com/NarcisPlan16/HA_Scheduler/tree/main/optimal_scheduler"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
apparmor: true
boot: manual
###############
# Try to solve api issues
homeassistant_api: true
auth_api: true
hassio_api: true
hassio_role: default
roles:
  - homeassistant
###############
map:
  - share:rw
  - addon_config:rw
  - addons:r
options:
  message: "Hello world..."
  Toggle_something: true
  Consumer_asset_IDs: []
  Generator_asset_IDs: []
  Energy_Source_asset_IDs: []
  Building_consumption_IDs: []

schema:
  message: "str?"
  Toggle_something: bool
  Consumer_asset_IDs: 
    - match(^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$)
  Generator_asset_IDs:
    - match(^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$)
  Energy_Source_asset_IDs:
    - match(^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$)
  Building_consumption_IDs:
    - match(^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$)


#image: "ghcr.io/NarcisPlan16/{arch}-optimal_scheduler"
