# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Optimal Scheduler
version: "2.4"
slug: optimal_scheduler
description: Scheduler & optimizer add-on for smart grids for energy management and cost savings.
url: "https://github.com/NarcisPlan16/HA_Scheduler/tree/main/optimal_scheduler"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
apparmor: true
boot: manual
# Try to solve api issues
homeassistant_api: true
#ingress: true
#ingress_port: 0
auth_api: true
hassio_api: true
hassio_role: homeassistant #default
roles:
  - homeassistant
###############
map:
  - share:rw
  - addon_config:rw
  - addons:r
options:
  message: "Hello world..."
  Toggle something: true
  Toggle something else: false

schema:
  message: "str?"
  Toggle something: bool
  Toggle something else: bool

args:
  BASHIO_VERSION: 0.16.2
  TEMPIO_VERSION: 2021.09.0
  
#image: "ghcr.io/NarcisPlan16/{arch}-optimal_scheduler"
