# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Optimal Scheduler
version: "1.2.4"
slug: optimal_scheduler
description: Scheduler & optimizer add-on for smart grids for energy management and cost savings.
url: "https://github.com/home-assistant/addons-example/tree/main/example"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  message: "Hello world..."
schema:
  message: "str?"
image: "ghcr.io/home-assistant/{arch}-addon-example"
